-- CREATE DATABASE kantor
-- CREATE TABLE office(
-- officeCode VARCHAR (10) NOT NULL,
-- city VARCHAR (50) NOT NULL,
-- phone VARCHAR (50) NOT NULL,
-- addressline1 VARCHAR (50) NOT NULL,
-- addressline2 VARCHAR (50),
-- state VARCHAR (50),
-- country VARCHAR (50) NOT NULL,
-- PRIMARY KEY(officeCode)
-- )
-- DESCRIBE office
-- ALTER TABLE office
-- MODIFY phone INT (20)
-- DROP addressline2